DEFAULT_MODEL_ID = "meta-llama/Meta-Llama-3-70B-Instruct"
DEFAULT_TEMPERATURE = 0.6
DEFAULT_TOP_P = 0.95
DEFAULT_FEW_SHOT_NUM = 3
DEFAULT_FEW_SHOT_SELECTION = "random"
DEFAULT_SAVE_INTERVAL = 10
DEFAULT_RES_DIR = "results"
DEFAULT_LOG_DIR = "logs"
