name: kg4s
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.4.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - scikit-learn
  - tqdm
  - click
  - pip
  - pip:
    - accelerate==0.31.0
    - arxiv==2.1.3
    - beautifulsoup4==4.12.3
    - black==24.4.2
    - gradio==4.40.0
    - pre-commit==3.7.1
    - spacy==3.7.5
    - transformers==4.37.2
    - wandb==0.17.4
    - psutil
    - packaging