name: kg4s
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.4.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy==2.0.1
  - pandas==2.2.2
  - scikit-learn==1.5.1
  - networkx==3.3
  - plotly==5.23.0
  - tqdm==4.66.4
  - click==8.1.7
  - pip
  - pip:
    - accelerate==0.33.0
    - arxiv==2.1.3
    - beautifulsoup4==4.12.3
    - black==24.4.2
    - fastapi
    - gradio==4.40.0
    - pre-commit==3.7.1
    - transformers==4.44.0
    - tabulate==0.9.0
    - wandb==0.17.4
    - psutil
    - packaging
    - uvicorn