name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gradio huggingface_hub

    - name: Deploy to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        python - <<EOF
        from huggingface_hub import HfApi
        import sys
        sys.path.append('scripts')
        from run_db_interface import demo
        
        api = HfApi()
        api.create_repo(
            repo_id="your-username/your-space-name",
            repo_type="space",
            space_sdk="gradio",
            token="$HF_TOKEN"
        )
        
        demo.deploy(
            repo_id="abby101/xurveyor-0",
            hf_token="$HF_TOKEN",
        )
        EOF