name: Run Python script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Gradio
      run: python -m pip install gradio

    - name: Deploy to Spaces
      env:
        HF_TOKEN: ${{ secrets.hf_token }}
      run: |
        python -c "import huggingface_hub; huggingface_hub.login(token='$HF_TOKEN', add_to_git_credential=True)"
        gradio deploy
